#! /usr/bin/env python
#
# Support module generated by PAGE version 4.5
# In conjunction with Tcl version 8.6
#    Jun 03, 2015 03:55:42 PM

from subprocess import call
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1


def exit_function():
    print('audioOutputSelect_support.exit_function')
    sys.stdout.flush()
    sys.exit()

def radio_button_function():
    if self.radiobutton_var.get() == "Auto":
        call(["sudo amixer cset numid=3 0"])
        print("Audio Set to Auto")
    if self.radiobutton_var.get() == "3.5MM":
        call(["sudo amixer cset numid=3 1"])
        print("Audio Set to 3.5MM Jack (Analog)")
    if self.radiobutton_var.get() == "HDMI":
        call(["sudo amixer cset numid=3 2"])
        print("Audio Set to HDMI")
    sys.stdout.flush()

def autoSelected():
    executeAmixerCall(0)
    print("Audio Set to Auto")

def analogSelected():
    executeAmixerCall(1)
    print("Audio Set to 3.5MM Jack (Analog)")

def hdmiSelected():
    executeAmixerCall(2)
    print("Audio Set to HDMI")

def executeAmixerCall(num):
    call(["sudo","amixer","cset","numid=3",str(num)])

def init(top, gui, arg=None):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None
